/*
 *  Copyright (C) 2000-2026  The Exult Team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifdef HAVE_CONFIG_H
#	include <config.h>
#endif

#include "cheat_screen.h"

#include "Configuration.h"
#include "Gump_manager.h"
#include "actors.h"
#include "cheat.h"
#include "cheat_screen_strings.h"
#include "chunks.h"
#include "exult.h"
#include "files/U7file.h"    // IWYU pragma: keep
#include "files/databuf.h"
#include "files/msgfile.h"
#include "files/utils.h"
#include "fnames.h"
#include "font.h"
#include "game.h"
#include "gameclk.h"
#include "gamemap.h"
#include "gamewin.h"
#include "gump_utils.h"
#include "ignore_unused_variable_warning.h"
#include "miscinf.h"
#include "party.h"
#include "scene_layer.h"
#include "schedule.h"
#include "touchui.h"
#include "ucmachine.h"
#include "version.h"
#include "vgafile.h"

#include <algorithm>
#include <cstring>

// disable the warning generated by using SDL_TOUCH_MOUSEID
#ifdef __GNUC__
#	pragma GCC diagnostic push
#	pragma GCC diagnostic ignored "-Wold-style-cast"
#	pragma GCC diagnostic ignored "-Wzero-as-null-pointer-constant"
#	if !defined(__llvm__) && !defined(__clang__)
#		pragma GCC diagnostic ignored "-Wuseless-cast"
#	endif
#endif    // __GNUC__
static const SDL_MouseID EXSDL_TOUCH_MOUSEID = SDL_TOUCH_MOUSEID;

// re-enable the warning
#ifdef __GNUC__
#	pragma GCC diagnostic pop
#endif    // __GNUC__

CheatScreen* CheatScreen::cscreen = nullptr;

int CheatScreen::Get_highest_map() {
	if (highest_map != INT_MIN) {
		return highest_map;
	}
	int n = 0;
	int next;
	while ((next = Find_next_map(n + 1, 10)) != -1) {
		n = next;
	}
	highest_map = n;
	return n;
}

void CheatScreen::screen_to_cheat(int ex, int ey, int& cx, int& cy) const {
	if (scene != nullptr && scene->valid()) {
		// Map through the scaled scene layer so input lines up with what is drawn.
		gwin->get_win()->screen_to_layer(scene->get_handle(), ex, ey, cx, cy);
	} else {
		gwin->get_win()->screen_to_game(ex, ey, gwin->get_fastmouse(), cx, cy);
	}
}

void CheatScreen::show_screen() {
	cscreen                              = this;
	ibuf                                 = gwin->get_win()->get_ib8();
	const str_int_pair& pal_tuple_static = game->get_resource("palettes/0");
	const str_int_pair& pal_tuple_patch  = game->get_resource("palettes/patch/0");
	pal.load(pal_tuple_static.str, pal_tuple_patch.str, pal_tuple_static.num);

	// init fontcolor transform table, default does nothing
	for (size_t i = 0; i < std::size(fontcolor.colors); i++) {
		fontcolor.colors[i]  = i;
		fontcolor2.colors[i] = i;
	}

	// Try to use SMALL_BLACK_FONT and Remap black to white in fontcolor
	font                 = fontManager.get_font("SMALL_BLACK_FONT");
	fontcolor.colors[0]  = pal.find_color(256, 256, 256);
	fontcolor2.colors[0] = pal.find_color(256, 0, 0);

	if (!font) {
		// reset fontcolor black so it maps to black
		fontcolor.colors[0] = 0;
		// Try to get the Font form Blackgate first because it looks better than
		// the SI one
		font = std::make_shared<Font>();
		if (font->load(U7MAINSHP_FLX, 9, 1) != 0) {
			font.reset();
		}
	}

	// Get the font for this game if don't already have it
	if (!font) {
		font = fontManager.get_font("MENU_FONT");
	}
	clock = gwin->get_clock();
	// Render the cheat screen into a fixed-size full-screen scene layer that is
	// scaled to fill the display using the main game video settings. 360x225
	// normally; 320x200 with the touch UI so its on-screen controls line up.
	const int   scene_w = (touchui != nullptr) ? 320 : 360;
	const int   scene_h = (touchui != nullptr) ? 200 : 225;
	Scene_layer scene_obj(scene_w, scene_h);
	scene = &scene_obj;
	if (scene_obj.valid()) {
		ibuf = scene_obj.buffer();
		maxx = scene_obj.width();
		maxy = scene_obj.height();
	} else {
		// No layer available: fall back to painting straight to the window.
		ibuf = gwin->get_win()->get_ib8();
		maxx = gwin->get_width();
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
		maxy = 200;
#else
		maxy = gwin->get_height();
#endif
	}
	centerx            = maxx / 2;
	centery            = maxy / 2;
	SDL_Window* window = gwin->get_win()->get_screen_window();
	if (touchui != nullptr) {
		touchui->hideGameControls();
		// Set the text input area to be just to the right of the prompt, and 10 pixels high.
		const int prompt_y = 81;
		const int input_x  = 64 + 15;
		TouchUI::setTextInputArea(window, input_x, prompt_y, maxx, prompt_y + 10);
		TouchUI::startTextInput(window);
	}

	// Pause the game
	gwin->get_tqueue()->pause(SDL_GetTicks());

	pal.apply();

	const int remaps[] = {
			5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5 - 1,
	};

	pal.Generate_remap_xformtable(highlighttable.colors, remaps);

	const int hoverremaps[] = {
			1, 1, 1, 1, 1, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 - 1,
	};

	pal.Generate_remap_xformtable(hovertable.colors, hoverremaps);

	// Make sure the font colour is properly remapped
	if (fontcolor[0]) {
		highlighttable.colors[fontcolor[0]] = highlighttable.colors[8];
		hovertable.colors[fontcolor[0]]     = hovertable.colors[8];
	}

	swipe = {};

	Mouse::mouse()->hide();
	Mouse::mouse()->set_shape(Mouse::hand);

	buttons_down.clear();
	// Run the Menu
	{
		const uint32 scene_mask = (1u << static_cast<int>(Image_window::UiLayerMousePointer))
								  | (1u << static_cast<int>(Image_window::UiLayerFullScreenScene));
		Game_window::Scoped_ui_layer_mask scene_layers(gwin, scene_mask);
		RunMenu(RootMenu());
	}
	// Make sure drawing is no longer redirected to the scene buffer (in case a
	// render loop broke out before its end_frame), then hide the scene layer
	// before the game view is repainted below; scene_obj's destructor removes it
	// entirely when show_screen returns. Point ibuf back at the game window so
	// nothing keeps a dangling reference to the scene buffer.
	scene_obj.restore_target();
	scene_obj.set_visible(false);
	scene = nullptr;
	ibuf  = gwin->get_win()->get_ib8();

	Mouse::mouse()->set_speed_cursor();
	Mouse::mouse()->hide();
	gwin->set_all_dirty();
	gwin->paint_dirty();

	// Resume the game clock
	gwin->get_tqueue()->resume(SDL_GetTicks());

	// Reset the palette
	clock->reset_palette();
	if (touchui != nullptr) {
		Gump_manager* gumpman = gwin->get_gump_man();
		if (!gumpman->gump_mode()) {
			touchui->showGameControls();
		}
		if (SDL_TextInputActive(window)) {
			SDL_StopTextInput(window);
		}
	}
}

const char* CheatScreen::getKeyName(SDL_Keycode keycode) {
	switch (keycode) {
	case SDLK_UNKNOWN:
		return "";

	case SDLK_ESCAPE:
		return Strings::ESC;

	case SDLK_TAB:
		return Strings::TAB;

	case SDLK_RETURN:
		return Strings::RET;

	case SDLK_BACKSPACE:
		return Strings::BACKSPACE;

		// Using a Macro for Function Keys because the keycodes for them aren't consecutive
#define F_KEY_CASE(n) \
	case SDLK_F##n:   \
		return "F" #n

		F_KEY_CASE(1);
		F_KEY_CASE(2);
		F_KEY_CASE(3);
		F_KEY_CASE(4);
		F_KEY_CASE(5);
		F_KEY_CASE(6);
		F_KEY_CASE(7);
		F_KEY_CASE(8);
		F_KEY_CASE(9);
		F_KEY_CASE(10);
		F_KEY_CASE(11);
		F_KEY_CASE(12);

		F_KEY_CASE(13);
		F_KEY_CASE(14);
		F_KEY_CASE(15);
		F_KEY_CASE(16);
		F_KEY_CASE(17);
		F_KEY_CASE(18);
		F_KEY_CASE(19);
		F_KEY_CASE(20);
		F_KEY_CASE(21);
		F_KEY_CASE(22);
		F_KEY_CASE(23);
		F_KEY_CASE(24);

#undef F_KEY_CASE
	default:
		// Get rid of the scancode bit
		int was_scancode = (keycode & SDLK_SCANCODE_MASK) ? 1 : 0;
		keycode &= ~SDLK_SCANCODE_MASK;

		if (keycode < 0x1000) {
			// Use a static array for each key name
			static char names[2][0x1000][4] = {};

			// only if not already set
			if (!names[was_scancode][keycode][0]) {
				// Keycode is an ASCII Character
				if (!was_scancode && keycode < 128 && std::isprint(keycode)) {
					names[was_scancode][keycode][0] = keycode;
					names[was_scancode][keycode][1] = 0;
				}
				// not ascii so output 3 digit hexcode
				else {
					for (size_t i = 0; i < 3; i++) {
						int  d                              = (keycode >> i * 4) & 0xf;
						char c                              = d + (d >= 0xA ? 'A' - 0xA : '0');
						names[was_scancode][keycode][2 - i] = c;
					}
					names[was_scancode][keycode][3] = 0;
				}
			}
			return names[was_scancode][keycode];
		}
	}
	return Strings::UNKNOWNKEYNAME;
}

//
// Input Handlers
//

// Parse the input , returns false on error
void CheatScreen::InputHandler::Parse() {
	if (!input[0]) {
		if (!empty_allowed) {
			throw MenuCommandException{Strings::INPUT_REQUIRED};
		} else {
			was_empty = true;
		}
	}
}

void CheatScreen::InputHandler::Arrange00Hotspots(int x, int y, unsigned lines) {
	size_t count00 = 0;
	for (const auto& hs : hotspots) {
		if (hs.x == 0 && hs.y == 0) {
			count00++;
		}
	}

	// If only one and it would fit put it on the bottom line
	if (count00 == 1 && x <= (320 - hotspots.back().getWidth())) {
		for (auto& hs : hotspots) {
			if (hs.x == 0 && hs.y == 0) {
				hs.x = x;
				hs.y = y + 9 * (lines - 1);
			}
		}
	}
	// One per line right align to edge of screen
	else if (lines >= count00) {
		for (auto& hs : hotspots) {
			if (hs.x == 0 && hs.y == 0) {
				hs.x = 320 - 8 - hs.getWidth();
				hs.y = y;
				y += 9;
			}
		}
	} else {    // put them all on 1 line
		for (auto& hs : hotspots) {
			if (hs.x == 0 && hs.y == 0) {
				hs.x = x;
				hs.y = y;
				x += hs.getWidth() + 8;
			}
		}
	}
}

int CheatScreen::InputHandler::PaintPrompt(int x, int y, SDL_Keycode lastkey) {
	auto  font      = cscreen->font;
	auto  ibuf      = cscreen->ibuf;
	auto& fontcolor = cscreen->fontcolor;
	int   offset    = font->paint_text_fixedwidth(ibuf, Strings::SELECT, x, y, 8, fontcolor.colors);
	if (curlen) {
		offset += font->paint_text_fixedwidth(ibuf, input, curlen, x + offset, y, 8, fontcolor.colors);
	} else {
		offset += cscreen->PaintKeyName(x + offset, y, lastkey);
	}

	return offset;
}

//
// KeyOnly and PressAKey input handlers
//

void CheatScreen::InputHandlers::KeyOnly::Parse() {
	if (!hotspots.empty()) {
		auto it = std::find_if(hotspots.begin(), hotspots.end(), [this](const auto& hotspot) {
			return hotspot.IsKeycode(key_sym);
		});
		if (it == hotspots.end()) {
			throw MenuCommandException{Strings::INVALID_COMMAND, false};
		}
	}
}

void CheatScreen::InputHandlers::PressAKey::GetPromptMessage(char* buf, size_t buf_size) {
	const char* pressmsg = Strings::PressAKey();
	if (promptmsg.empty()) {
		snprintf(buf, buf_size, "%s", pressmsg);
		// If buf is too small to fit entire press message, don't append it
	} else if ((promptmsg.size() + strlen(pressmsg)) >= buf_size) {
		snprintf(buf, buf_size, "%s", promptmsg.c_str());
	} else {
		snprintf(buf, buf_size, "%s %s", promptmsg.c_str(), pressmsg);
	}
}

//
// String Input Handler
//

CheatScreen::InputHandlers::String::String(bool empty_allowed, std::string&& promptmsg, std::string&& invalidmsg)
		: InputHandler(empty_allowed, std::move(promptmsg)), invalidmsg(std::move(invalidmsg)) {}

bool CheatScreen::InputHandlers::String::OnInput(SDL_Keycode key_sym) {
	// Backspace last character
	if (key_sym == SDLK_BACKSPACE) {
		if (curlen) {
			input[--curlen] = 0;
		}
	}
	// Append the character
	else if (key_sym < 256 && std::isprint(key_sym)) {
		if (curlen < (std::size(input) - 1)) {
			input[curlen++] = key_sym;
			input[curlen]   = 0;
		}
	} else if (key_sym == SDLK_RETURN) {
		return true;
	}

	return false;
}

void CheatScreen::InputHandlers::String::Parse() {
	if (!curlen && !empty_allowed) {
		throw MenuCommandException{invalidmsg, false};
	}
}

//
// Integer Input Handler
//

inline void CheatScreen::InputHandlers::Integer::GetPromptMessage(char* buf, size_t buf_size) {
	bool hasmin = val_min != INT_MIN;
	bool hasmax = val_max != INT_MAX;
	// treat as hex if hex only flag is set or the input has a hex prefix
	bool hex = hexonly || !strncmp(input, "0x", 2) || !strncmp(input, "-0x", 3);

	if (hasmin && hasmax) {
		snprintf(buf, buf_size, (hex ? "%s 0x%x-0x%x " : "%s %d-%d "), promptmsg.c_str(), val_min, val_max);
	} else if (hasmin || hasmax) {
		snprintf(
				buf, buf_size, (hex ? "%s%s0x%x " : "%s%s%d "), promptmsg.c_str(), hasmin ? Strings::Min_() : Strings::Max_(),
				hasmin ? val_min : val_max);

	} else {
		snprintf(buf, buf_size, "%s ", promptmsg.c_str());
	}
}

bool CheatScreen::InputHandlers::Integer::OnInput(SDL_Keycode key_sym) {
	// treat as hex if hex only flag is set or the input has a hex prefix
	bool hex = hexonly || !strncmp(input, "0x", 2) || !strncmp(input, "-0x", 3);

	// Increment/Decrement with arrow keys
	if (key_sym == SDLK_LEFT || key_sym == SDLK_RIGHT) {
		char* end     = nullptr;
		input[curlen] = 0;
		long val      = std::strtol(input, &end, hex ? 16 : 10);

		if (end == input + curlen) {
			// Decrement
			if (key_sym == SDLK_LEFT && val > val_min) {
				val--;
			}
			// Increment
			else if (key_sym == SDLK_RIGHT && val < val_max) {
				val++;
			} else {
				val = val_min;
			}
			// Format value back to a string
			// Separate handling for positive and negative so negative hex numbers have a minus sign
			int len = 0;
			if (val < 0) {
				len = snprintf(input, std::size(input), hex ? "-%lx" : "-%ld", -val);
			} else {
				len = snprintf(input, std::size(input), hex ? "%lx" : "%ld", val);
			}
			if (len < 0) {
				curlen   = 0;
				input[0] = 0;
				throw MenuCommandException{"Unexpected Error calling snprintf", false};
			}
			if (size_t(len) >= std::size(input)) {
				input[curlen = std::size(input) - 1] = 0;
			} else {
				curlen = len;
			}
		}
	}
	// Add x for hex prefix but only if input is currently "0" or "-0" to form "0x or "-0x
	else if ((key_sym == SDLK_X) && (!strcmp(input, "0") || !strcmp(input, "-0"))) {
		input[curlen++] = 'x';
		input[curlen]   = 0;
	}
	// Backspace last character
	else if (key_sym == SDLK_BACKSPACE) {
		if (curlen) {
			input[--curlen] = 0;
		}
	}
	// Append pressed digit, or minus sign if start of input
	else if (key_sym < 256 && (std::isdigit(key_sym) || (hex && std::isxdigit(key_sym)) || (key_sym == SDLK_MINUS && !input[0]))) {
		if (curlen < (std::size(input) - 1)) {
			// SDLK_MINUS should be '-' but being careful I'm not assuming that
			input[curlen++] = key_sym == SDLK_MINUS ? '-' : char(std::tolower(key_sym));
			input[curlen]   = 0;
		}
	} else if (key_sym == SDLK_RETURN) {
		return true;
	}

	return false;
}

CheatScreen::InputHandlers::Integer::Integer(
		bool empty_allowed, int min, int max, bool hex, std::string&& promptmsg, std::string&& invalidmsg,
		std::optional<int> special, std::function<bool(Integer*)> validate)
		: InputHandler(empty_allowed, std::move(promptmsg)), hexonly(hex), val_min(std::min(max, min)), val_max(std::max(max, min)),
		  invalidmsg(std::move(invalidmsg)), special(special), validate(validate) {}

CheatScreen::InputHandlers::Integer::Integer(bool empty_allowed, int min, int max, bool hex, std::string&& promptmsg)
		: Integer(empty_allowed, min, max, hex, std::move(promptmsg), Strings::INVALID_VALUE) {}

CheatScreen::InputHandlers::Integer::Integer(bool empty_allowed, int min, int max, bool hex)
		: Integer(empty_allowed, min, max, hex, Strings::ENTER_VALUE) {}

void CheatScreen::InputHandlers::Integer::Parse() {
	InputHandler::Parse();

	if (empty_allowed && was_empty) {
		// If empty set to minimum
		value = val_min;
		return;
	}

	// treat as hex if hex only flag is set or the input has a hex prefix
	bool hex = hexonly || !strncmp(input, "0x", 2) || !strncmp(input, "-0x", 3);

	if (input[0]) {
		char* input_end = nullptr;

		const long val = std::strtol(input, &input_end, hex ? 16 : 10);
		if (input_end != input && ((val >= val_min && val <= val_max) || special.value_or(val_min) == val)) {
			value = int(val);
		} else {
			throw MenuCommandException{invalidmsg, false};
		}
	}

	if (validate && !validate(this)) {
		throw MenuCommandException{invalidmsg, false};
	}
}

//
// Game Object input Handler
//

CheatScreen::InputHandlers::GameObject::GameObject(bool empty_allowed, std::string&& promptmsg, std::string&& invalidmsg)
		: Integer(empty_allowed, 0, gwin->get_num_npcs() - 1, false, std::move(promptmsg), std::move(invalidmsg)) {
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
	const int offsety = 90;
#else
	const int offsety = cscreen->maxy - 9;
#endif
	const char* label = Strings::Pick_Object_from_World;
	hotspots.emplace_back(0, offsety, label[0], label + 1);
	hotspots.back().PositionLeftOf();
}

CheatScreen::InputHandlers::GameObject::GameObject(bool empty_allowed, std::string&& promptmsg)
		: GameObject(empty_allowed, std::move(promptmsg), Strings::INVALID_OBJECT) {}

CheatScreen::InputHandlers::GameObject::GameObject(bool empty_allowed) : GameObject(empty_allowed, Strings::ENTERNPCNUMBER) {}

bool CheatScreen::InputHandlers::GameObject::OnInput(SDL_Keycode key_sym) {
	// Enter Pick Mode
	if (hotspots[0].IsKeycode(key_sym)) {
		cscreen->WaitButtonsUp(true);
		// Temporarily hide the scene layer so the game world is visible while
		// the user picks an object; the next menu frame re-shows the scene.
		if (cscreen->scene != nullptr) {
			cscreen->scene->set_visible(false);
		}
		gwin->set_all_dirty();
		gwin->paint();
		gwin->show(true);

		int x, y;

		bool result = Get_click(x, y, Mouse::greenselect, nullptr, true, nullptr, true);
		cscreen->pal.apply(false);
		if (result) {
			object = gwin->find_object(x, y);
		} else {
			throw MenuCommandException{Strings::CANCELLED, false};
		}
		if (!object) {
			throw MenuCommandException{invalidmsg, false};
		}
		return true;
	}
	return Integer::OnInput(key_sym);
}

void CheatScreen::InputHandlers::GameObject::Parse() {
	if (!object) {
		Integer::Parse();

		// Empty input means use grabbed NPC
		if (empty_allowed && was_empty) {
			object = cscreen->grabbed;
		} else {
			object = gwin->get_npc(value);
		}
	}

	if (!object) {
		throw MenuCommandException{invalidmsg};
	}
}

//
// Shape input Handler
//

CheatScreen::InputHandlers::Shape::Shape(bool empty_allowed, bool wantframenum)
		: Integer(empty_allowed, 0, sman->get_shapes().get_num_shapes() - 1, false, Strings::ENTER_SHAPE, Strings::INVALID_SHAPE),
		  wantframenum(wantframenum) {
	const char* label = Strings::Browse;
	hotspots.emplace_back(0, 0, label[0], label + 1);
}

bool CheatScreen::InputHandlers::Shape::OnInput(SDL_Keycode key_sym) {
	// Enter browse Mode
	if (hotspots[0].IsKeycode(key_sym)) {
		cscreen->WaitButtonsUp(true);
		cheat.shape_browser();

		if (!cheat.get_browser_shape(shapenum, framenum)) {
			throw MenuCommandException{Strings::WRONG_SHAPE_FILE_MUST_BE_SHAPES_VGA, false};
		}

		// Clear framenum if its not explicitly ask for
		if (!wantframenum) {
			framenum = -1;
		}

		return true;
	}
	if (Integer::OnInput(key_sym)) {
		if (!wantframenum) {
			return true;
		}

		Integer::Parse();
		if (shapenum == -1) {
			shapenum = value;
			Integer::clear();
			promptmsg = Strings::ENTER_FRAME;
			val_min   = 0;
			val_max   = sman->get_shapes().get_num_frames(shapenum) - 1;

			if (sman->get_shapes().get_shape(shapenum)->is_rle() && val_max == 31) {
				// Allow reflection framenums for RLE shapes with 31 frames
				val_max |= 32;
			}

		} else {
			framenum = value;
			return true;
		}
	}
	return false;
}

void CheatScreen::InputHandlers::Shape::Parse() {
	if (shapenum == -1) {
		Integer::Parse();
		shapenum = value;
	}
	//
	value = -1;
}

void CheatScreen::InputHandlers::Shape::clear() {
	Integer::clear();
	promptmsg = Strings::ENTER_SHAPE;
	shapenum  = -1;
	framenum  = -1;
	val_min   = 0;
	val_max   = Shape_manager::get_instance()->get_shapes().get_num_shapes() - 1;
}

//
// DISPLAYS
//

static void resizeline(float& axis1, float delta1, float& axis2) {
	if (axis1) {
		float slope = axis2 / axis1;
		axis1 += delta1;
		axis2 = axis1 * slope;
	}
}

SDL_Keycode CheatScreen::GetKey(const std::vector<Hotspot*>& hotspots, SDL_Keycode& unicode) {
	SDL_Event     event;
	SDL_Renderer* renderer = SDL_GetRenderer(gwin->get_win()->get_screen_window());
	SDL_Window*   window   = gwin->get_win()->get_screen_window();
	// Do repaint after 100 ms to allow for time dependent effects. 10 FPS seems
	// more that adequate for Cheat Screen If anyone needs to do smooth animation
	// they can change this
	auto repainttime = SDL_GetTicks() + 100;
	Mouse::mouse()->hide();    // Turn off mouse.
	std::memset(&event, 0, sizeof(event));

	while (SDL_GetTicks() < repainttime) {
		Delay();

		// How far finger needs to move for swipe to be interpreted as an a
		// cursor key input)
		bool do_swipe = std::abs(swipe.dx) > swipe_threshold || std::abs(swipe.dy) > swipe_threshold;

		if (!do_swipe && swipe.last && ((swipe.last + 200) < SDL_GetTicks())) {
			// zero out swipe state if it's been longer that 200ms since last
			// event recieved and it's shorter than the threshold
			swipe.last = 0;
			swipe.dx   = 0;
			swipe.dy   = 0;
		}
		Mouse::mouse_update = false;
		while (do_swipe || SDL_PollEvent(&event)) {
			int         gx, gy;
			SDL_Keycode simulate_key = SDLK_UNKNOWN;

			//
			if (do_swipe) {
				float ax = 0, ay = 0;
				ay = std::abs(swipe.dy);
				ax = std::abs(swipe.dx);
				CERR("Doing swipe ay: " << ay << " ax:" << ax);
				// More vertical motion or More Horizontal
				// perfectly diagonal motion will be treated as horizontal
				if (ay > ax) {
					// Swipe up the screen
					if (swipe.dy < -swipe_threshold) {
						simulate_key = SDLK_UP;
						resizeline(swipe.dy, +swipe_threshold, swipe.dx);
						// Swipe Down the screen
					} else if (swipe.dy > swipe_threshold) {
						simulate_key = SDLK_DOWN;
						resizeline(swipe.dy, -swipe_threshold, swipe.dx);
					}
				} else {
					// swipe right to left
					if (swipe.dx < -swipe_threshold) {
						simulate_key = SDLK_LEFT;
						resizeline(swipe.dx, +swipe_threshold, swipe.dy);
						// Swipe left to right
					} else if (swipe.dx > swipe_threshold) {
						simulate_key = SDLK_RIGHT;
						resizeline(swipe.dx, -swipe_threshold, swipe.dy);
					}
				}
			} else {
				CERR("event.type= " << event.type);
				switch (event.type) {
				case SDL_EVENT_QUIT: {
					CERR("SDL_EVENT_QUIT");
					ImageBufferPaintable screenshot;
					if (gwin->get_gump_man()->okay_to_quit(&screenshot)) {
						throw quit_exception();
					}
				} break;
				case SDL_EVENT_FINGER_DOWN: {
					CERR("SDL_EVENT_FINGER_DOWN");
					buttons_down.insert(button_down_finger);
					if ((!Mouse::use_touch_input) && (event.tfinger.fingerID != 0)) {
						Mouse::use_touch_input = true;
					}
					break;
				}
				case SDL_EVENT_FINGER_UP: {
					CERR("SDL_EVENT_FINGER_UP");
					// Get iterator for first instance of button_down_finger and
					// erase it from the collection
					auto it = buttons_down.find(button_down_finger);
					if (it != buttons_down.end()) {
						buttons_down.erase(it);
					}
				} break;
					// Finger swiping converts to cursor keys
				case SDL_EVENT_FINGER_MOTION: {
					gwin->get_win()->screen_to_game(event.button.x, event.button.y, gwin->get_fastmouse(), gx, gy);

					static int numFingers = 0;
					SDL_GetTouchFingers(event.tfinger.touchID, &numFingers);
					CERR("numFingers " << numFingers);

					// Will allow single finger swipes
					if (numFingers > 0) {
						// Hide on screen keyboard if we are swiping
						if (SDL_TextInputActive(window)) {
							SDL_StopTextInput(window);
						}
						// Accumulate the deltas onto
						// the vector
						swipe.dx += event.tfinger.dx;
						swipe.dy += event.tfinger.dy;
						// set last swipe value to now
						swipe.last = SDL_GetTicks();
					}
				} break;

				// Mousewheel scrolling with SDL2.
				case SDL_EVENT_MOUSE_WHEEL: {
					CERR("SDL_EVENT_MOUSE_WHEEL");
					if (event.wheel.y > 0) {
						simulate_key = SDLK_LEFT;
					} else if (event.wheel.y < 0) {
						simulate_key = SDLK_RIGHT;
					}
				} break;
				case SDL_EVENT_MOUSE_MOTION: {
					CERR("SDL_EVENT_MOUSE_MOTION");
					if (Mouse::use_touch_input && event.motion.which != EXSDL_TOUCH_MOUSEID) {
						Mouse::use_touch_input = false;
					}
					gwin->get_win()->screen_to_game(event.motion.x, event.motion.y, gwin->get_fastmouse(), gx, gy);

					Mouse::mouse()->move(gx, gy);
					// Track the pointer in cheat-screen (scene) coordinates for
					// hotspot hover/hit-testing.
					screen_to_cheat(event.motion.x, event.motion.y, cheat_mousex, cheat_mousey);
					Mouse::mouse_update = true;
				} break;
					// return;

				case SDL_EVENT_MOUSE_BUTTON_DOWN: {
					SDL_ConvertEventToRenderCoordinates(renderer, &event);
					screen_to_cheat(event.button.x, event.button.y, gx, gy);
					cheat_mousex = gx;
					cheat_mousey = gy;
					CERR("SDL_EVENT_MOUSE_BUTTON_DOWN( " << gx << " , " << gy << " )");
					buttons_down.insert(event.button.button);
					if (event.button.button == 1) {
						simulate_key = Hotspot::HitCheck(hotspots, gx, gy);

						if (!simulate_key) {
							// Double click detection
							if (event.button.clicks >= 2) {
								simulate_key = SDLK_RETURN;
							}

							// Touch on the cheat screen will bring up the
							// keyboard but not if the tap was within a 20 pixel
							// border on the edge of the cheat screen.
							if (SDL_TextInputActive(window)) {
								SDL_StopTextInput(window);
							} else if (gx > 20 && gy > 20 && gx < (maxx - 20) && gy < (maxy - 20)) {
								TouchUI::startTextInput(window);
							}
						}
					}
				} break;
				case SDL_EVENT_MOUSE_BUTTON_UP: {
					buttons_down.erase(event.button.button);
				} break;

				case SDL_EVENT_KEY_DOWN: {
					buttons_down.insert(int(event.key.key));
				} break;

				case SDL_EVENT_KEY_UP: {
					buttons_down.erase(int(event.key.key));
				} break;

				default:
					break;
				}
			}

			if (simulate_key) {
				std::memset(&event, 0, sizeof(event));
				event.type    = SDL_EVENT_KEY_DOWN;
				event.key.key = simulate_key;
				CERR("simmulate key " << event.key.key);
			}
			if (event.type != SDL_EVENT_KEY_DOWN) {
				continue;
			}
			SDL_Keycode key_sym = event.key.key;
			SDL_Keymod  key_mod = event.key.mod;
			unicode             = 0;
			if (!Translate_keyboard(event, key_sym, unicode, true)) {
				continue;
			}

			if ((key_sym == SDLK_S) && (key_mod & SDL_KMOD_ALT) && (key_mod & SDL_KMOD_CTRL)) {
				make_screenshot(true);
				return SDLK_UNKNOWN;
			}

			return key_sym;
		}
		gwin->rotatecolours();
		Mouse::mouse()->show();    // Re-display mouse.
		if (gwin->show() || Mouse::mouse_update) {
			Mouse::mouse()->blit_dirty();
		}
		Mouse::mouse()->hide();    // Need to immediately turn off here to prevent
								   // flickering after repaint of whole screen
	}
	// Didn't get a key press before the timeout
	return SDLK_UNKNOWN;
}

void CheatScreen::RunMenu(std::shared_ptr<Menu> menu) {
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
	const int offsetx  = 15;
	const int prompty  = 81;
	const int promptx  = 15;
	const int offsety5 = 72;
#else
	const int offsetx  = 0;
	const int prompty  = maxy - 18;
	const int promptx  = 0;
	const int offsety5 = maxy - 36;
#endif

	std::shared_ptr<MenuCommand> message_command = std::make_shared<MenuCommand>();
	Uint32                       messagetime     = 0;
	Hotspot                      EscapeHotspot   = {offsetx + 160, offsety5 + 9, SDLK_ESCAPE, ""};

	message_command->inputs.push_back(std::make_shared<InputHandlers::PressAKey>());
	std::stack<std::shared_ptr<MenuCommand>> input_stack;
	std::weak_ptr<MenuCommand>               last = {};
	std::vector<Hotspot*>                    hotspots;
	input_stack.push(menu);

	Uint32      highlighted   = SDLK_UNKNOWN;
	Uint32      highlighttime = 0;
	SDL_Keycode key_sym = SDLK_UNKNOWN;     // This is they key that was pressed, it can persist over multiple loops and gets set to
											// 0 after an exception is caught
	SDL_Keycode last_key = SDLK_UNKNOWN;    // Last key that was pressed, used to display what key was pressed next to the prompt
	SDL_Keycode unicode  = SDLK_UNKNOWN;

	// While the input stack is not empty run it
	while (!input_stack.empty()) {
		auto current = input_stack.top();
		// Track the last command that had input so if the active command changes the input phase is always reset but ignore
		// message_command so commands can throw message exceptions and not lose the input they already have
		if (current != last.lock()) {
			current->ResetPhase();

			if (current != message_command) {
				last = current;
			}
		}

		try {
			while (current && current->BeginPhase()) {
				// Current Input Handler that needs to receive input
				InputHandler* ih = current->GetInputHandler();

				for (;;) {
					current->run();
					hotspots.clear();
					if (scene && scene->valid()) {
						scene->begin_frame();
					} else {
						gwin->clear_screen();
					}
					current->paint_display();
					current->GatherHotspots(hotspots);

					if (dynamic_cast<Menu*>(current.get())
						|| (current == message_command && dynamic_cast<Menu*>(current->below.get()))) {
						// Menus show escape hotspot with Exit label
						// message_command is treated as a menu if a menu is below it in the stack
						EscapeHotspot.label_rw = Strings::Exit();
					} else {
						// Non menus show To Cancel label
						EscapeHotspot.label_rw = Strings::TO_CANCEL();
					}

					// Add Escape hotspot
					hotspots.push_back(&EscapeHotspot);

					// 41 is big enough as the screen res is only big enough for 40x25 text
					char buf[41];

					ih->GetPromptMessage(buf, std::size(buf));
					// Null terminate it just to be sure
					buf[std::size(buf) - 1] = 0;
					int promptmsgwidth      = font->paint_text_fixedwidth(ibuf, buf, promptx, prompty + 9, 8, fontcolor.colors);

					int cursor_offset = ih->PaintPrompt(promptx, prompty, last_key);
					// Paint flashing cursor
					if (SDL_GetTicks() % (2 * cursorflashtime) > cursorflashtime) {
						font->paint_text_fixedwidth(
								ibuf, Strings::CURSOR, promptx + cursor_offset, prompty, 8,
								ih->input_full() ? fontcolor2.colors : fontcolor.colors);
					}
					ih->Arrange00Hotspots(promptx + promptmsgwidth + 8, prompty, 2);
					ih->GatherHotspots(hotspots);

					if (highlighttime && highlighttime < SDL_GetTicks()) {
						highlighted   = SDLK_UNKNOWN;
						highlighttime = 0;
					}
					if (messagetime && messagetime < SDL_GetTicks()) {
						highlighted = SDLK_UNKNOWN;
						messagetime = 0;
						if (current == message_command) {
							current = nullptr;
							break;
						}
					}
					for (const auto hs : hotspots) {
						hs->Paint(highlighted, cheat_mousex, cheat_mousey);
					}
					if (scene && scene->valid()) {
						scene->end_frame();
					}
					Mouse::mouse()->show();
					gwin->get_win()->show();
					Mouse::mouse()->hide();    // Must immediately hide to prevent flickering
					last_key = key_sym = GetKey(hotspots, unicode);

					if (key_sym != SDLK_UNKNOWN) {
						// Highlight the key
						highlighttime = SDL_GetTicks() + highlighttimeout;
						highlighted   = key_sym;

						// Escape always leaves current and doesn't get passed to input handler
						if (key_sym == SDLK_ESCAPE) {
							// If not Showing the Message Command throw the exception to return to the previousmenu
							if (current != message_command) {
								// Show Cancelled Message if not leaving a menu
								throw MenuCommandException{
										!dynamic_cast<Menu*>(current.get()) ? Strings::CANCELLED : std::string(), true};
							}
							current->cancelled();
							current = nullptr;
							break;
						} else if (ih->OnInput(key_sym)) {
							ih->Parse();
							break;
						}
					}
				}

				// Current could be gone here
				if (current) {
					current->EndPhase();
				}
			}
			auto command = current;

			// Activate the command now that all it's needed input phases are done Replace the command with the result of Activate
			if (command) {
				command = command->Activate(key_sym);
			}

			// New Command so put it at the top of the stack
			if (command) {
				command->ResetPhase();

				// Don't push onto stack if we are already top
				if (command != input_stack.top()) {
					command->below = input_stack.top();
					input_stack.push(command);
					// reset highlight so things don't get highlighted incorrectly on a different menu
					if (dynamic_cast<Menu*>(command.get())) {
						highlighttime = 0;
						highlighted   = SDLK_UNKNOWN;
					}
				}
			}
			// New command is null, pop top of stack
			else {
				input_stack.pop();
			}
		} catch (MenuCommandException& ex) {
			if (ex.return_to_menu || current->NumPhases() == 0) {
				// pop till we reach a menu or nothing
				do {
					input_stack.top()->cancelled();
					input_stack.pop();
				} while (!input_stack.empty() && dynamic_cast<Menu*>(input_stack.top().get()) == nullptr);
			}
			// If the message is empty don't try to show it
			if (!ex.msg.empty()) {
				message_command->below = input_stack.top();

				message_command->inputs[0]->SetPromptMessage(std::move(ex.msg));
				input_stack.push(message_command);
				messagetime = SDL_GetTicks() + messagetimeout;
				if (current->Ready()) {
					current->UnReady();
				}
			}
		}
	}

	WaitButtonsUp();
}

void CheatScreen::Hotspot::PositionLeftOf(const Hotspot* hotspot) {
	if (hotspot) {
		// positionn to left of hotspot
		// copy y coord
		y = hotspot->y;
		x = hotspot->x - getWidth();
	} else {
		// position to left of right edge of screen or 320 which is smaller
		x = std::min(320, cscreen->maxx) - getWidth();
	}
}

SDL_Keycode CheatScreen::Hotspot::HitCheck(const std::vector<Hotspot*>& hotspots, int mx, int my, int distance) {
	// Find the nearest hotspot
	SDL_Keycode nearest     = SDLK_UNKNOWN;
	int         nearestdist = INT_MAX;

	for (auto hs : hotspots) {
		if (hs) {
			for (size_t k = 0; k < std::size(hs->keycode); k++) {
				TileRect rect = hs->GetRect(k, false);
				int      dist = rect.distance(mx, my);
				if (rect && dist < nearestdist) {
					nearest     = hs->keycode[k];
					nearestdist = dist;
				}
			}
		}
	}
	// Only return it if it is within the radius
	if (nearestdist <= distance) {
		return FixUppercaseKeycode(nearest);
	}
	return SDLK_UNKNOWN;
}

std::shared_ptr<CheatScreen::Menu> CheatScreen::RootMenu() {
	std::forward_list<Menu::Item> items;
	std::shared_ptr<MenuCommand>  command;
	const char*                   label;

#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
	const int offsetx  = 15;
	const int offsety1 = 73;
	const int offsety2 = 55;
	const int offsetx1 = 160;
	const int offsety4 = 36;
#else
	const int offsetx  = 0;
	const int offsety1 = 0;
	const int offsety2 = 0;
	const int offsetx1 = 0;
	const int offsety4 = maxy - 45;
#endif

	// Left Column

	// Paperdolls
#if !defined(SDL_PLATFORM_IOS) && !defined(ANDROID) && !defined(CHEAT_SCREEN_TEST_MOBILE)
	// Paperdolls can be toggled in the gumps, no need here for small screens
	Shape_manager* sman = Shape_manager::get_instance();

	command = std::make_shared<ToggleCommand>(
			sman->can_use_paperdolls() && sman->are_paperdolls_enabled(), Strings::NoYes.ToArray());
	command->events.Activate = [](MenuCommand*, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		Shape_manager* sman = Shape_manager::get_instance();

		if ((Game::get_game_type() == BLACK_GATE || Game::get_game_type() == EXULT_DEVEL_GAME) && sman->can_use_paperdolls()) {
			sman->set_paperdoll_status(!sman->are_paperdolls_enabled());
			config->set("config/gameplay/bg_paperdolls", sman->are_paperdolls_enabled() ? "yes" : "no", true);
		}
		return {};
	};
	label = Strings::RootMenu::Paperdolls;
	items.emplace_front(Hotspot(offsetx, maxy - 99, label[0], label + 1), command);
#endif

	// GodMode
	command                  = std::make_shared<ToggleCommand>(cheat.in_god_mode(), Strings::OffOn.ToArray());
	command->events.Activate = [](MenuCommand*, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		cheat.toggle_god();
		return {};
	};
	label = Strings::RootMenu::GodMode;
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 90, label[0], label + 1), command);

	// Archwizard Mode
	command                  = std::make_shared<ToggleCommand>(cheat.in_wizard_mode(), Strings::OffOn.ToArray());
	command->events.Activate = [](MenuCommand*, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		cheat.toggle_wizard();
		return {};
	};
	label = Strings::RootMenu::WizardMode;
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 81, label[0], label + 1), command);

	// Infravision
	command                  = std::make_shared<ToggleCommand>(cheat.in_infravision(), Strings::OffOn.ToArray());
	command->events.Activate = [](MenuCommand*, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		cheat.toggle_infravision();
		return {};
	};
	label = Strings::RootMenu::Infravision;
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 72, label[0], label + 1), command);

	// Hackmover
	command                  = std::make_shared<ToggleCommand>(cheat.in_hack_mover(), Strings::OffOn.ToArray());
	command->events.Activate = [](MenuCommand*, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		cheat.toggle_hack_mover();
		return {};
	};
	label = Strings::RootMenu::HackMover;
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 63, label[0], label + 1), command);

	// Eggs
	command                  = std::make_shared<ToggleCommand>(gwin->paint_eggs, Strings::NoYes.ToArray());
	command->events.Activate = [](MenuCommand*, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		cheat.toggle_eggs();
		return {};
	};
	label = Strings::RootMenu::EggsVisible;
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 54, label[0], label + 1), command);

	// Set Time
	// Menu command has 3 integer input handlers for day, hour and minute
	// Activate lambda gets the values from the input handlers and sets the new day and time
	command = std::make_shared<MenuCommand>();
	command->inputs.push_back(
			std::make_shared<InputHandlers::Integer>(false, 0, INT_MAX, false, Strings::ENTER_DAY, Strings::INVALID_TIME));
	command->inputs.push_back(
			std::make_shared<InputHandlers::Integer>(false, 0, 23, false, Strings::ENTER_HOUR, Strings::INVALID_TIME));
	command->inputs.push_back(
			std::make_shared<InputHandlers::Integer>(false, 0, 59, false, Strings::ENTER_MINUTE, Strings::INVALID_TIME));
	command->events.Activate = [this](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		clock->reset();
		clock->set_day(static_cast<InputHandlers::Integer*>(self->inputs[0].get())->value);
		clock->set_hour(static_cast<InputHandlers::Integer*>(self->inputs[1].get())->value);
		clock->set_minute(static_cast<InputHandlers::Integer*>(self->inputs[2].get())->value);
		// Return to Menu and show clock set message
		throw MenuCommandException{Strings::CLOCK_SET, true};
	};
	label = Strings::RootMenu::SetTime;
	items.emplace_front(Hotspot(offsetx + offsetx1, offsety4, label[0], label + 1), command);

	// Right Column

	// NPC Tool
	// This Menu Command has an input handler to get an NPC,
	// then returns the NPCMenu for the NPC in the Activate lambda
	command                  = std::make_shared<MenuCommand>();
	command->events.Activate = [this](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		return NPCMenu(static_cast<InputHandlers::Actor*>(self->inputs[0].get())->actor);
	};
	command->inputs.push_back(std::make_shared<InputHandlers::Actor>(true));
	label = Strings::RootMenu::NPCTool;
	items.emplace_front(Hotspot(offsetx + 160, maxy - offsety2 - 99, label[0], label + 1), command);

	// Usecode Menu
	// just directly adds the menu as a menu item
	label = Strings::RootMenu::Usecode;
	items.emplace_front(Hotspot(offsetx + 160, maxy - offsety2 - 90, label[0], label + 1), UsecodeMenu());

	// Teleport Menu
	// just directly adds the menu as a menu item
	label = Strings::RootMenu::Teleport;
	items.emplace_front(Hotspot(offsetx + 160, maxy - offsety2 - 81, label[0], label + 1), TeleportMenu());

	// Time Rate
#if !defined(SDL_PLATFORM_IOS) && !defined(ANDROID) && !defined(CHEAT_SCREEN_TEST_MOBILE)
	// for small screens taking the liberty of leaving that out
	command                  = std::make_shared<LeftRightIntegerCommand>(1, 20, clock->get_time_rate());
	command->events.Activate = [this](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		clock->set_time_rate(static_cast<LeftRightIntegerCommand*>(self)->currentval);
		return {};
	};
	items.emplace_front(Hotspot(offsetx + 160, offsety4, SDLK_LEFT, Strings::RootMenu::TimeRate(), SDLK_RIGHT), command);
#endif

	std::shared_ptr<Menu> menu = std::make_shared<Menu>(std::move(items));
	menu->events.paint_display = [this](MenuCommand*) {
		char buf[512];
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
		const int offsetx  = 15;
		const int offsety1 = 108;
		const int offsety2 = 54;
		const int offsety3 = 0;
#else
		const int offsetx  = 0;
		const int offsety1 = 0;
		const int offsety2 = 0;
		const int offsety3 = 45;
#endif
		const int        curmap = gwin->get_map()->get_num();
		const Tile_coord t      = gwin->get_main_actor()->get_tile();

		font->paint_text_fixedwidth(ibuf, Strings::AdvancedOptionCheatScreen, offsetx, offsety1, 8, fontcolor.colors);

		std::string gametitle = Game::get_menustring();
		size_t      pos;
		// Replace all newlines in title with ": "
		while ((pos = gametitle.find('\n')) != std::string::npos) {
			gametitle.replace(pos, 1, ": ");
		}
		snprintf(buf, sizeof(buf), "%s\"%s\"", Strings::Running(), gametitle.c_str());

		font->paint_text_fixedwidth(ibuf, buf, offsetx, offsety1 + 18, 8, fontcolor.colors);

		strcpy(buf, "Exult Version " VERSION " Rev: ");
		auto rev    = VersionGetGitRevision(true);
		int  curlen = strlen(buf);
		rev.copy(buf + strlen(buf), rev.size());
		// Need to null terminate after copy
		buf[curlen + rev.size()] = 0;
		font->paint_text_fixedwidth(ibuf, buf, offsetx, offsety1 + 27, 8, fontcolor.colors);

		font->paint_text_fixedwidth(ibuf, "Compiled " __DATE__ " " __TIME__, offsetx, offsety1 + 36, 8, fontcolor.colors);

		snprintf(
				buf, sizeof(buf), "%s%i:%02i %s  %s%i", Strings::CurrentTime(), ((clock->get_hour() + 11) % 12) + 1,
				clock->get_minute(), clock->get_hour() < 12 ? Strings::am() : Strings::pm(), Strings::Day(), clock->get_day());
		font->paint_text_fixedwidth(ibuf, buf, offsetx, offsety3, 8, fontcolor.colors);

		const int longi = ((t.tx - 0x3A5) / 10);
		const int lati  = ((t.ty - 0x46E) / 10);
		snprintf(
				buf, sizeof(buf), "%s%d %s %d %s, %s%d", Strings::Coordinates(), abs(lati),
				(lati < 0 ? Strings::North() : Strings::South()), abs(longi), (longi < 0 ? Strings::West() : Strings::East()),
				Strings::Map(), curmap);
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 63 - offsety2, 8, fontcolor.colors);

		snprintf(buf, sizeof(buf), "%s(%04x, %04x, %02x)", Strings::Coords_hex(), t.tx, t.ty, t.tz);
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 72 - offsety2, 8, fontcolor.colors);

		snprintf(buf, sizeof(buf), "%s(%04i, %04i, %02i)", Strings::Coords_dec(), t.tx, t.ty, t.tz);
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 81 - offsety2, 8, fontcolor.colors);
		return true;
	};
	return menu;
}

int CheatScreen::PaintArrow(int offsetx, int offsety, int type) {
	// Need to draw arrows with overlapping characters
	// up arrow
	if (type == '^') {
		// Use an i as the stem of the arrow
		font->paint_text_fixedwidth(ibuf, "i", offsetx, offsety, 8, fontcolor.colors);
		// Draw a black line to narrow the stem
		ibuf->draw_line8(0, offsetx + 4, offsety, offsetx + 4, offsety + 8);
		// Draw point of arrow
		font->paint_text_fixedwidth(ibuf, "^", offsetx, offsety, 8, fontcolor.colors);
	}    // down arrow
	else if (type == 'V') {
		// Use an l as the stem of the arrow
		font->paint_text_fixedwidth(ibuf, "l", offsetx, offsety, 8, fontcolor.colors);
		// Draw black lines to narrow the stem
		ibuf->draw_line8(0, offsetx + 2, offsety, offsetx + 2, offsety + 2);
		ibuf->draw_line8(0, offsetx + 4, offsety, offsetx + 4, offsety + 6);

		// Draw point of arrow
		font->paint_text_fixedwidth(ibuf, "m", offsetx, offsety + 2, 8, fontcolor.colors);

		// Paint black lines to make it pointy
		ibuf->draw_line8(0, offsetx + 0, offsety + 5, offsetx + 0, offsety + 8);
		ibuf->draw_line8(0, offsetx + 6, offsety + 5, offsetx + 6, offsety + 8);
		ibuf->draw_line8(0, offsetx + 1, offsety + 6, offsetx + 1, offsety + 8);
		ibuf->draw_line8(0, offsetx + 5, offsety + 6, offsetx + 5, offsety + 8);
	}    // left arrow
	else if (type == '<') {
		// Stem of arrow
		font->paint_text_fixedwidth(ibuf, "-", offsetx + 1, offsety, 8, fontcolor.colors);
		// Paint black line  to narrow the stem
		ibuf->draw_line8(0, offsetx + 0, offsety + 4, offsetx + 7, offsety + 4);
		// Point of  arrow
		font->paint_text_fixedwidth(ibuf, "<", offsetx, offsety, 8, fontcolor.colors);
		// Paint black line to make it pointier
		ibuf->draw_line8(0, offsetx + 1, offsety + 4, offsetx + 4, offsety + 7);
		ibuf->put_pixel8(0, offsetx + 5, offsety + 7);
	}    // Right Arrow
	else if (type == '>') {
		// Stem of arrow
		font->paint_text_fixedwidth(ibuf, "-", offsetx, offsety, 8, fontcolor.colors);
		// Paint black line to narrow the stem
		ibuf->draw_line8(0, offsetx + 0, offsety + 4, offsetx + 7, offsety + 4);
		// Point of arrow
		font->paint_text_fixedwidth(ibuf, ">", offsetx + 2, offsety, 8, fontcolor.colors);
		// Paint black line to make it pointier
		ibuf->draw_line8(0, offsetx + 7, offsety + 4, offsetx + 3, offsety + 7);
	} else {
		return 0;
	}

	return 8;
}

//
// Usecode
//
std::shared_ptr<CheatScreen::Menu> CheatScreen::UsecodeMenu() {
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
	const int offsetx  = 15;
	const int offsety1 = 64;
#else
	const int offsetx  = 0;
	const int offsety1 = 0;
#endif
	std::forward_list<Menu::Item> items;
	std::shared_ptr<MenuCommand>  command;
	const char*                   label;

	// Left Column

	// Call Usecode
	// 3 input handlers
	// One for Target Object
	// One for Usecode function number
	// One for event id
	command = std::make_shared<MenuCommand>();
	command->inputs.push_back(std::make_shared<InputHandlers::GameObject>(false));
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(
			false, 0, gwin->get_usecode()->get_num_funcs() - 1, false, Strings::UsecodeMenu::Prompts::Enterusecodenumber,
			Strings::UsecodeMenu::Prompts::InvalidUsecodeNumber, std::nullopt, [](InputHandlers::Integer* self) -> bool {
				return gwin->get_usecode()->function_exists(self->value);
			}));
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(
			false, 0, int(Usecode_machine::num_events) - 1, false, Strings::UsecodeMenu::Prompts::EnterUsecodeEventid,
			Strings::UsecodeMenu::Prompts::InvalidUsecodeEventNumber));
	command->events.begin_phase = [=](MenuCommand* self) {
		// Get the object from input 0 and get its usecode function number and prefill input[1]
		if (self->phase == 1) {
			auto object_h = static_cast<InputHandlers::GameObject*>(self->inputs[0].get());
			auto ucnum_ih = static_cast<InputHandlers::Integer*>(self->inputs[1].get());

			int ucnum = object_h->object->get_usecode();
			if (gwin->get_usecode()->function_exists(ucnum)) {
				char buf[16];
				snprintf(buf, std::size(buf), "0x%x", ucnum);
				ucnum_ih->SetInput(buf);
			}
		}
	};
	command->events.Activate = [this](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		auto target_input   = static_cast<InputHandlers::GameObject*>(self->inputs[0].get());
		auto ucnum_input    = static_cast<InputHandlers::Integer*>(self->inputs[1].get());
		auto eventnum_input = static_cast<InputHandlers::Integer*>(self->inputs[2].get());
		auto usecode        = gwin->get_usecode();
		// Always Reload usecode before calling so modders don't need to do it manually every time they want to test a change
		usecode->read_usecode();
		// Calling usecode might do things that use a different event loop so first wait for button ups
		cscreen->WaitButtonsUp(true);
		usecode->call_usecode(ucnum_input->value, target_input->object, Usecode_machine::Usecode_events(eventnum_input->value));
		// apply palette because usecode may have changed it
		pal.apply(false);

		return {};
	};
	label = Strings::UsecodeMenu::MenuItems::CallUsecode;
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 99, label[0], label + 1), command);

	// Reload Usecode
	command                  = std::make_shared<MenuCommand>();
	command->events.Activate = [](MenuCommand*, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		gwin->get_usecode()->read_usecode();
		return {};
	};
	label = Strings::UsecodeMenu::MenuItems::ReloadUsecode;
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 90, label[0], label + 1), command);

	// Global Flag Editors
	// 1 input handler foor flag number
	command = std::make_shared<MenuCommand>();
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(
			false, 0, Usecode_machine::last_gflag, false, Strings::ENTER_GLOBAL_FLAG, Strings::INVALID_VALUE));
	label                    = Strings::UsecodeMenu::MenuItems::FlagEditor;
	command->events.Activate = [this](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		// Load global flag names if not yet loaded
		if (!global_flag_names_loaded) {
			load_global_flag_names();
		}
		return GlobalFlagMenu(static_cast<InputHandlers::Integer*>(self->inputs[0].get())->value);
	};
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 81, label[0], label + 1), command);

	auto menu = std::make_shared<Menu>(std::move(items));

	menu->events.paint_display = [this](MenuCommand*) -> bool {
		char buf[41];

#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
		const int offsetx = 15;
#else
		const int offsetx = 0;
#endif

#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
		snprintf(
				buf, sizeof(buf), "%s - %s!", Strings::UsecodeMenu::Display::UsecodeMenu(),
				Strings::UsecodeMenu::Display::Dangerous());
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 0, 8, fontcolor.colors);
#else
		font->paint_text_fixedwidth(ibuf, Strings::UsecodeMenu::Display::UsecodeMenu, offsetx, 0, 8, fontcolor.colors);
		snprintf(
				buf, sizeof(buf), "%s - %s!", Strings::UsecodeMenu::Display::Dangerous(),
				Strings::UsecodeMenu::Display::usewithcare());
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 18, 8, fontcolor.colors);
#endif

		return true;
	};

	return menu;
}

//
// Global Flags
//

void CheatScreen::load_global_flag_names() {
	global_flag_names_loaded = true;
	if (is_system_path_defined("<PATCH>") && U7exists(PATCH_GLOBAL_FLAGS)) {
		IFileDataSource flagsfile(PATCH_GLOBAL_FLAGS, true);
		if (flagsfile.good()) {
			Text_msg_file_reader reader(flagsfile);
			reader.get_global_section_strings(global_flag_names);
		}
	} else {
		const str_int_pair& resource = game->get_resource("files/global_flags");
		IExultDataSource    flagsfile(resource.str, resource.num);
		if (flagsfile.good()) {
			Text_msg_file_reader reader(flagsfile);
			reader.get_global_section_strings(global_flag_names);
		}
	}
}

std::shared_ptr<CheatScreen::Menu> CheatScreen::GlobalFlagMenu(unsigned num) {
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
	const int offsetx  = 15;
	const int offsety1 = 83;
#else
	const int offsetx  = 0;
	const int offsety1 = 0;
#endif
	std::forward_list<Menu::Item> items;

	// Global Flag number Messageuses a label only hotspot
	// uses run event to update the label of the Hotspot
	auto command        = std::make_shared<MenuCommand>();
	command->events.run = [this](MenuCommand* self) {
		char buf[16];
		auto num = MenuCommand::getDataOrDefault<unsigned>(self->GetMyMenu());
		snprintf(buf, sizeof(buf), "%d ", num);
		std::string_view flag_name;

		if (num < static_cast<unsigned>(global_flag_names.size()) && !global_flag_names[num].empty()) {
			flag_name = global_flag_names[num];
		} else {
			flag_name = Strings::AdvancedFlagsMenu::unnamed();
		}
		if (auto hotspot = self->getHotspot()) {
			hotspot->label_rw.reserve(hotspot->label.size() + 16 + flag_name.size());

			hotspot->label_rw = hotspot->label;
			hotspot->label_rw += buf;
			hotspot->label_rw += flag_name;
			hotspot->label_only = true;
		}
	};
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 99, 0, Strings::AdvancedFlagsMenu::GlobalFlag), command);

	// Flag is set/unset message uses a label only hotspot
	// uses run event to update the label of the Hotspot
	command             = std::make_shared<MenuCommand>();
	command->events.run = [](MenuCommand* self) {
		auto num = MenuCommand::getDataOrDefault<unsigned>(self->GetMyMenu());

		if (auto hotspot = self->getHotspot()) {
			hotspot->label_rw = gwin->get_usecode()->get_global_flag_bool(num) ? Strings::AdvancedFlagsMenu::FlagIsSET()
																			   : Strings::AdvancedFlagsMenu::FlagIsUNSET();
			;
			hotspot->label_only = true;
		}
	};
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 90, 0, ""), command);

	// Toggle command
	command                  = std::make_shared<MenuCommand>();
	command->events.Activate = [](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		auto num = MenuCommand::getDataOrDefault<unsigned>(self->GetMyMenu());
		gwin->get_usecode()->set_global_flag(num, !gwin->get_usecode()->get_global_flag_bool(num));
		return {};
	};
	const char* label = Strings::AdvancedFlagsMenu::ToggleFlag;
	if (label && *label) {
		items.emplace_front(Hotspot(offsetx + 160, maxy - offsety1 - 90, *label, label + 1), command);
	}

	// Change Flag
	command = std::make_shared<MenuCommand>();
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(
			false, 0, Usecode_machine::last_gflag, false, Strings::ENTER_GLOBAL_FLAG, Strings::INVALID_VALUE));
	command->events.Activate = [](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		self->GetMyMenu()->setData<unsigned>(static_cast<InputHandlers::Integer*>(self->inputs[0].get())->value);

		return {};
	};
	items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 72, SDLK_UP, Strings::AdvancedFlagsMenu::ChangeFlag), command);

	// Scroll Flags
	command                  = std::make_shared<LeftRightIntegerCommand>(0, Usecode_machine::last_gflag, 0, false);
	command->events.Activate = [](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		self->GetMyMenu()->setData<unsigned>(static_cast<LeftRightIntegerCommand*>(self)->currentval);
		return {};
	};
	command->events.run = [](MenuCommand* self) {
		// Make sure currentval is synced with the flag number
		static_cast<LeftRightIntegerCommand*>(self)->currentval = MenuCommand::getDataOrDefault<unsigned>(self->GetMyMenu());
	};
	items.emplace_front(
			Hotspot(offsetx, maxy - offsety1 - 63, SDLK_LEFT, Strings::AdvancedFlagsMenu::ScrollFlags, SDLK_RIGHT), command);

	auto menu = std::make_shared<Menu>(std::move(items));
	menu->setData<unsigned>(num);

	menu->events.paint_display = [=](MenuCommand*) -> bool {
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
		font->paint_text_fixedwidth(ibuf, Strings::AdvancedFlagsMenu::GlobalFlags, 15, 0, 8, fontcolor.colors);
		return true;
#else
		return false;
#endif
	};
	return menu;
}

//
// Teleport screen
//

std::shared_ptr<CheatScreen::Menu> CheatScreen::TeleportMenu() {
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
	const int offsetx  = 15;
	const int offsety1 = 64;
	const int offsetx2 = 175;
	const int offsety2 = 63;
	const int offsety3 = 90;
#else
	const int offsetx  = 8;
	const int offsety1 = 0;
	const int offsetx2 = offsetx;
	const int offsety2 = maxy - 63;
	const int offsety3 = maxy - 9;
#endif
	std::forward_list<Menu::Item> items;
	const char*                   label;
	std::shared_ptr<MenuCommand>  command;
	//
	// Left Column
	//

	// Geographic
	// 4 input handlers
	// KeyOnly to select north or south
	// Integer to enter latitude
	// KeyOnly to select East or West
	// Integer to enter longitude
	// Run event is used to update mins and max values of Integer input handlers based on the North/South or East/West InputHandlers

	command                         = std::make_shared<MenuCommand>();
	const char*          labelNorth = Strings::TeleportMenu::NorthOr;
	const char*          labelSouth = Strings::TeleportMenu::South;
	const char*          labelWest  = Strings::TeleportMenu::WestOr;
	const char*          labelEast  = Strings::TeleportMenu::East;
	std::vector<Hotspot> hotspots;
	hotspots.reserve(2);
	hotspots.emplace_back(0, offsety3, labelNorth[0], labelNorth + 1);
	hotspots.emplace_back(0, offsety3, labelSouth[0], labelSouth + 1);
	// Hotspot 1(South) is placed on right edgeof screen
	hotspots[1].PositionLeftOf();
	// Notspot 0(North) is placed to the left of Hotspot 1(South)
	hotspots[0].PositionLeftOf(&(hotspots[1]));

	command->inputs.push_back(std::make_shared<InputHandlers::KeyOnly>(Strings::TeleportMenu::Latitude, std::move(hotspots)));
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(false, 0, 193, false, Strings::ENTER_LATITUDE));

	// reinitialized moved hotspots vector just to be safe
	hotspots = std::vector<Hotspot>();
	hotspots.emplace_back(0, offsety3, labelWest[0], labelWest + 1);
	hotspots.emplace_back(0, offsety3, labelEast[0], labelEast + 1);

	// Hotspot 1(East) is placed on right edge of screen
	hotspots[1].PositionLeftOf();
	// Notspot 0(West) is placed to the left of Hotspot 1(East)
	hotspots[0].PositionLeftOf(&(hotspots[1]));

	command->inputs.push_back(std::make_shared<InputHandlers::KeyOnly>(Strings::TeleportMenu::Longitude, std::move(hotspots)));
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(false, 0, 193, false, Strings::ENTER_LONGITUDE));

	command->events.begin_phase = [=](MenuCommand* self) {
		// Check phase 0 input and update maximum accepted for input[1]
		if (self->phase == 1) {
			auto latkeypress = static_cast<InputHandlers::KeyOnly*>(self->inputs[0].get());
			auto latinteger  = static_cast<InputHandlers::Integer*>(self->inputs[1].get());

			latinteger->setMax(latkeypress->check_key(*labelNorth) ? 113 : 193);
		}
		// Check phase 2 input and update maximum accepted for input[3]
		else if (self->phase == 3) {
			auto longkeypress = static_cast<InputHandlers::KeyOnly*>(self->inputs[2].get());
			auto longinteger  = static_cast<InputHandlers::Integer*>(self->inputs[3].get());

			longinteger->setMax(longkeypress->check_key(*labelWest) ? 93 : 213);
		}
	};
	command->events.Activate = [=](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		Tile_coord t;
		auto       latkeypress  = static_cast<InputHandlers::KeyOnly*>(self->inputs[0].get());
		auto       latinteger   = static_cast<InputHandlers::Integer*>(self->inputs[1].get());
		auto       longkeypress = static_cast<InputHandlers::KeyOnly*>(self->inputs[2].get());
		auto       longinteger  = static_cast<InputHandlers::Integer*>(self->inputs[3].get());
		if (latkeypress->check_key(*labelNorth)) {
			t.ty = ((latinteger->value * -10) + 0x46E);
		} else {
			t.ty = ((latinteger->value * 10) + 0x46E);
		}
		if (longkeypress->check_key(*labelWest)) {
			t.tx = ((longinteger->value * -10) + 0x3A5);
		} else {
			t.tx = ((longinteger->value * 10) + 0x3A5);
		}
		t.tz = 0;
		gwin->teleport_party(t);

		return {};
	};

	label = Strings::TeleportMenu::GeographicCoordinates;
	if (*label) {
		items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 90, *label, label + 1), command);
	}

	// Tile Coords
	command = std::make_shared<MenuCommand>();
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(false, 0, c_num_tiles, false, Strings::ENTER_X_COORD));
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(false, 0, c_num_tiles, false, Strings::ENTER_Y_COORD));
	command->inputs.push_back(std::make_shared<InputHandlers::Integer>(false, 0, 255, false, Strings::ENTER_Z_COORD));
	command->events.Activate = [=](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		Tile_coord t
				= {static_cast<InputHandlers::Integer*>(self->inputs[0].get())->value,
				   static_cast<InputHandlers::Integer*>(self->inputs[1].get())->value,
				   static_cast<InputHandlers::Integer*>(self->inputs[2].get())->value};
		gwin->teleport_party(t);

		return {};
	};
	label = Strings::TeleportMenu::TileCoordinates;
	if (*label) {
		items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 81, *label, label + 1), command);
	}

	// NPC
	command = std::make_shared<MenuCommand>();
	command->inputs.push_back(std::make_shared<InputHandlers::Actor>(false));
	command->events.Activate = [=](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
		if (Actor* actor = static_cast<InputHandlers::Actor*>(self->inputs[0].get())->actor) {
			if (!actor->get_chunk()) {
				// No teleporting to NPC not on map
				throw MenuCommandException{Strings::TeleportMenu::CantTeleporttoNPCnotonmap, false};
			} else {
				gwin->teleport_party(actor->get_tile(), false, actor->get_map_num());
			}
		}

		return {};
	};
	label = Strings::TeleportMenu::NPCNumber;
	if (*label) {
		items.emplace_front(Hotspot(offsetx, maxy - offsety1 - 72, *label, label + 1), command);
	}

	// Map
	const int highest = Get_highest_map();

	if (highest != 0) {
		command = std::make_shared<MenuCommand>();
		command->inputs.push_back(std::make_shared<InputHandlers::Integer>(false, 0, highest, false, Strings::ENTER_VALUE));
		command->events.Activate = [=](MenuCommand* self, SDL_Keycode) -> std::shared_ptr<MenuCommand> {
			gwin->teleport_party(
					gwin->get_main_actor()->get_tile(), true, static_cast<InputHandlers::Integer*>(self->inputs[0].get())->value);

			return {};
		};
		label = Strings::TeleportMenu::MapNumber;
		items.emplace_front(Hotspot(offsetx2, offsety2, *label, label + 1), command);
	}

	auto menu                  = std::make_shared<Menu>(std::move(items));
	menu->events.paint_display = [this](MenuCommand*) -> bool {
		char             buf[512];
		const Tile_coord t       = gwin->get_main_actor()->get_tile();
		const int        curmap  = gwin->get_map()->get_num();
		const int        highest = Get_highest_map();
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
		const int offsetx  = 15;
		const int offsety1 = 54;
#else
		const int offsetx  = 0;
		const int offsety1 = 0;
#endif

#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
		snprintf(buf, sizeof(buf), "%s - %s!", Strings::TeleportMenu::Teleport_Menu(), Strings::TeleportMenu::Dangerous());
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 0, 8, fontcolor.colors);
#else
		font->paint_text_fixedwidth(ibuf, Strings::TeleportMenu::Teleport_Menu, offsetx, 0, 8, fontcolor.colors);
		snprintf(buf, sizeof(buf), "%s - %s!", Strings::TeleportMenu::Dangerous(), Strings::TeleportMenu::UseWithCare());
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 18, 8, fontcolor.colors);
#endif

		const int longi = ((t.tx - 0x3A5) / 10);
		const int lati  = ((t.ty - 0x46E) / 10);
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
		snprintf(
				buf, sizeof(buf), "%s%d %s %d %s, %s%d %s %d", Strings::TeleportMenu::Coords(), abs(lati),
				(lati < 0 ? Strings::North() : Strings::South()), abs(longi), (longi < 0 ? Strings::West() : Strings::East()),
				Strings::Map(), curmap, Strings::TeleportMenu::Of(), highest + 1);
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 9, 8, fontcolor.colors);
#else
		snprintf(
				buf, sizeof(buf), "%s%d %s %d %s", Strings::Coordinates(), abs(lati),
				(lati < 0 ? Strings::North() : Strings::South()), abs(longi), (longi < 0 ? Strings::West() : Strings::East()));
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 63, 8, fontcolor.colors);
#endif

		snprintf(buf, sizeof(buf), "%s(%04x, %04x, %02x)", Strings::Coords_hex(), t.tx, t.ty, t.tz);
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 72 - offsety1, 8, fontcolor.colors);

		snprintf(buf, sizeof(buf), "%s(%04i, %04i, %02i)", Strings::Coords_dec(), t.tx, t.ty, t.tz);
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 81 - offsety1, 8, fontcolor.colors);

#if !defined(SDL_PLATFORM_IOS) && !defined(ANDROID) && !defined(CHEAT_SCREEN_TEST_MOBILE)
		snprintf(buf, sizeof(buf), "%s%d %s %d", Strings::TeleportMenu::OnMap(), curmap, Strings::TeleportMenu::Of(), highest + 1);
		font->paint_text_fixedwidth(ibuf, buf, offsetx, 90, 8, fontcolor.colors);
#endif

		return true;
	};

	return menu;
}

int CheatScreen::PaintKeyName(int offsetx, int offsety, SDL_Keycode keycode) {
	switch (keycode) {
	case SDLK_UP:
		return PaintArrow(offsetx, offsety, '^');
	case SDLK_DOWN:
		return PaintArrow(offsetx, offsety, 'V');
	case SDLK_LEFT:
		return PaintArrow(offsetx, offsety, '<');
	case SDLK_RIGHT:
		return PaintArrow(offsetx, offsety, '>');
	case SDLK_UNKNOWN:
		return 0;
	default:
		return font->paint_text_fixedwidth(ibuf, getKeyName(keycode), offsetx, offsety, 8, fontcolor.colors);
	}
}

CheatScreen::Hotspot::Hotspot(int x, int y, SDL_Keycode keycode1, std::string&& label, SDL_Keycode keycode2)
		: keycode{keycode1, keycode2}, namew{GetKeyNameWidth(keycode1), GetKeyNameWidth(keycode2)}, label(std::move(label)),
		  label_only(keycode1 == 0 && keycode2 == 0), x(x), y(y) {}

void CheatScreen::Hotspot::Paint(SDL_Keycode highlighted, int hoverx, int hovery) const {
	auto  font       = cscreen->font;
	auto& fontcolor  = cscreen->fontcolor;
	auto  ibuf       = cscreen->ibuf;
	int   nameswidth = 0;

	// Don't paint keys if in label only mode
	if (!label_only) {
		// No keycodes, paint nothing
		if (GetNumkeycodes() == 0) {
			return;
		}

		for (size_t k = 0; k < std::size(keycode); ++k) {
			if (keycode[k] && !hide[k]) {
				cscreen->PaintKeyName(x + 8 + nameswidth, y, keycode[k]);
			}
			nameswidth += namew[k] * 8;
		}

		font->paint_text_fixedwidth(ibuf, "[", x, y, 8, fontcolor.colors);
		font->paint_text_fixedwidth(ibuf, "]", x + nameswidth + 8, y, 8, fontcolor.colors);
	}

	int labelstart = (nameswidth ? 16 : 0) + nameswidth;
	int labelwidth = font->paint_text_fixedwidth(ibuf, get_label().c_str(), x + labelstart, y, 8, fontcolor.colors);
	for (size_t k = 0; k < std::size(keycode); ++k) {
		TileRect r = GetRect(k, false);

		if (keycode[k] && !hide[k]) {
			if (FixUppercaseKeycode(keycode[k]) == FixUppercaseKeycode(highlighted)) {
				ibuf->fill_translucent8(0, r.w, r.h, r.x, r.y, cscreen->highlighttable);
				ibuf->fill_translucent8(0, labelwidth, 8, x + labelstart, y, cscreen->highlighttable);
			}
			if (r.has_point(hoverx, hovery)) {
				ibuf->fill_translucent8(0, r.w, r.h, r.x, r.y, cscreen->hovertable);
			}
		}
	}
}

void CheatScreen::WaitButtonsUp(bool silent) {
	Uint32 show_message = SDL_GetTicks() + 1000;

	SDL_Keycode           keycode;
	std::vector<Hotspot>  hotspots;
	std::vector<Hotspot*> hotspotptrs;
	while (buttons_down.size()) {
		{
			SDL_Keycode unicode;
			keycode = GetKey(hotspotptrs, unicode);
		}
		if (scene && scene->valid()) {
			scene->begin_frame();
		} else {
			gwin->clear_screen();
		}

		// exit if escape is pressed
		if (keycode == SDLK_ESCAPE) {
			// But first eat up events if there are any
			SDL_Keycode unicode;
			GetKey({}, unicode);
			break;
		}

		if (!silent && show_message < SDL_GetTicks()) {
#if defined(SDL_PLATFORM_IOS) || defined(ANDROID) || defined(CHEAT_SCREEN_TEST_MOBILE)
			const int offsetx_start = 15;
			const int offsetx1      = 160;
			const int offsety5      = 72;
#else
			const int offsetx_start = 0;
			const int offsetx1      = 160;
			const int offsety5      = maxy - 36;
#endif

			int         offsetx     = offsetx_start;
			const char* msg_waiting = Strings::Waitingforupevents;
			int         offsety     = 36;
			offsetx                 = offsetx1 - 4 * strlen(msg_waiting);
			offsetx += font->paint_text_fixedwidth(ibuf, msg_waiting, offsetx, offsety, 8, fontcolor.colors);

			bool first       = true;
			int  last_button = 0;
			for (int button : buttons_down) {
				char        buf[80]     = {0};
				const char* button_name = nullptr;

				// only each button once.. Standard guarantees that all keys
				// that compare equivalent are grouped together
				if (button == last_button) {
					continue;
				}
				last_button = button;

				switch (button) {
				case button_down_finger: {
					size_t num_fingers = buttons_down.count(button_down_finger);
					button_name        = buf;

					if (num_fingers > 1) {
						snprintf(buf, sizeof(buf), "%zu %s", num_fingers, Strings::Fingers());
					} else {
						button_name = Strings::Finger;
					}
				} break;

				case 1:
				case 2:
				case 3: {
					// Don't show mouse buttons if also waiting for finger
					// up
					if (buttons_down.find(button_down_finger) != buttons_down.end()) {
						continue;
					}

					button_name = Strings::MouseButton[button - 1];
				} break;

				default: {
					// It should be an SDL_Keycode
					const char* keyname = SDL_GetKeyName(SDL_Keycode(button));
					button_name         = buf;

					// Only display keyname if there is one and it is in ASCII
					if (keyname[0] && std::none_of(keyname, keyname + strlen(keyname), [](char c) {
							return static_cast<unsigned char>(c) >= 128;
						})) {
						snprintf(buf, sizeof(buf), "%s%s", Strings::Key(), keyname);
					} else {
						snprintf(buf, sizeof(buf), "%s%i", Strings::UnknownKey_(), button);
					}
				} break;
				}

				if (!first) {
					// Paint a comma at the end of the previous name
					offsetx += font->paint_text_fixedwidth(ibuf, ", ", offsetx, offsety, 8, fontcolor.colors);
				}
				first = false;

				// check if we have enough space on this line for the keyname
				// if not start a new line
				if (offsetx + strlen(button_name) * 8 > 312) {
					offsetx = offsetx_start;
					offsety += 9;
					// If we advance so many lines just break out now
					if (offsety >= (offsety5 + 9)) {
						break;
					}
				} else {
				}

				offsetx += font->paint_text_fixedwidth(ibuf, button_name, offsetx, offsety, 8, fontcolor.colors);
			}

			offsetx               = 0;
			const char* msg_press = Strings::Press;
			font->paint_text_fixedwidth(ibuf, msg_press, offsetx + 160 - 8 * strlen(msg_press), offsety5 + 9, 8, fontcolor.colors);

			if (hotspots.empty()) {
				hotspotptrs.push_back(&hotspots.emplace_back(offsetx + 160, offsety5 + 9, SDLK_ESCAPE, Strings::toexitnow));
			}
		}

		for (auto& hs : hotspots) {
			hs.Paint(SDLK_UNKNOWN, cheat_mousex, cheat_mousey);
		}
		if (scene && scene->valid()) {
			scene->end_frame();
		}
		Mouse::mouse()->show();
		gwin->get_win()->show();
		Mouse::mouse()->hide();    // Must immediately hide to prevent flickering
	}
}

CheatScreen::Menu::Menu(std::forward_list<Menu::Item>&& items) : items(std::move(items)) {
	// Set the hotspot for all our menu items
	for (auto& pair : this->items) {
		if (pair.second) {
			pair.second->hotspot = &pair.first;
			pair.second->owner   = this;
		}
	}

	// Input handler to select Menu items
	inputs.emplace_back(std::make_unique<InputHandlers::KeyOnly>(Strings::ENTER_COMMAND));
}

std::shared_ptr<CheatScreen::MenuCommand> CheatScreen::Menu::Activate(SDL_Keycode keycode) {
	// Returns the MenuCommand associted with the keycode

	auto it = std::find_if(items.begin(), items.end(), [keycode](const auto& pair) {
		return pair.first.IsKeycode(keycode);
	});
	if (it != items.end()) {
		return it->second;
	} else if (keycode == SDLK_RETURN || keycode == SDLK_RETURN2) {
		// Silently ignore presses of return by returning ourself
		return shared_from_this();
	}
	throw MenuCommandException{Strings::INVALID_COMMAND, false};
}
